runtime: nodejs20
instance_class: F1
entrypoint: npm start

env_variables:
  NODE_ENV: 'production'
  PORT: '8080'
  TM_API_KEY: ''
  SPOTIFY_CLIENT_ID: ''
  SPOTIFY_CLIENT_SECRET: ''
  MONGODB_URI:''


